steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcb-notifier/gcb-notifier:$COMMIT_SHA',
                  '-t', 'gcr.io/$PROJECT_ID/gcb-notifier/gcb-notifier:latest',
                  '.']
images:
- 'gcr.io/$PROJECT_ID/gcb-notifier/gcb-notifier:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/gcb-notifier/gcb-notifier:latest'
